### ISSUE TITLE
Not support -rev option ?

### ISSUE THREAD

**Issue by archersmind** [Freescale/imx-mkimage#2]
I'm working on a project that using below command line to generate the image

`imx-mkimage/mkimage_imx8 -soc QX -rev B0 -append imx-mkimage/mx8qx-ahab-container.img -c -flags 0x00010000 -scfw imx-mkimage/scfw_tcm_b0.bin -ap ipl-imx8qxp-cpu.bin a35 0x80000000  -out ipl-imx8qxp-cpu_b0.bin`

Error returned says 

> option '' is invalid: ignored

I think` -rev` is not support right ? Can you support `-rev` option in next version ?

**Comment by archersmind** [comment]
I found an updated version on the codeaurora https://source.codeaurora.org/external/imx/imx-mkimage. Thank you

**Comment by otavio** [comment]
So maybe, propose a patch to update it?
